// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Xuw8iG6hM1zm6158WGC8ujKkds3TfUQ',
    appId: '1:877873003418:web:7cb15bd674dc1f80715823',
    messagingSenderId: '877873003418',
    projectId: 'student-management-syste-bb312',
    authDomain: 'student-management-syste-bb312.firebaseapp.com',
    storageBucket: 'student-management-syste-bb312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVvg8Pdj72wsYAR80nSz4iYDiPyZnR_Y',
    appId: '1:877873003418:android:47aeffbcb2cd98db715823',
    messagingSenderId: '877873003418',
    projectId: 'student-management-syste-bb312',
    storageBucket: 'student-management-syste-bb312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdSLQZPZ0svdQhMxhJGqw6usvLkrLM9k',
    appId: '1:877873003418:ios:d7ffbe51f402c645715823',
    messagingSenderId: '877873003418',
    projectId: 'student-management-syste-bb312',
    storageBucket: 'student-management-syste-bb312.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdSLQZPZ0svdQhMxhJGqw6usvLkrLM9k',
    appId: '1:877873003418:ios:d7ffbe51f402c645715823',
    messagingSenderId: '877873003418',
    projectId: 'student-management-syste-bb312',
    storageBucket: 'student-management-syste-bb312.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Xuw8iG6hM1zm6158WGC8ujKkds3TfUQ',
    appId: '1:877873003418:web:7f491a207ea7ca98715823',
    messagingSenderId: '877873003418',
    projectId: 'student-management-syste-bb312',
    authDomain: 'student-management-syste-bb312.firebaseapp.com',
    storageBucket: 'student-management-syste-bb312.firebasestorage.app',
  );
}
