import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:student_registration_system/screens/login_screen.dart';
import 'package:student_registration_system/theme/app_theme.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Student Registration System',
     theme: AppTheme.lightTheme,
      home: const LoginScreen(),
    );
  }
}

